--//// ATENCAO//////
-- Executar separadamente:


create or replace TRIGGER AUDITORIA_USUARIO
BEFORE UPDATE OR DELETE ON USUARIO
FOR EACH ROW
BEGIN
  INSERT INTO TRILHA_AUDITORIA (IDTRILHA_AUDITORIA, USUARIO_IDUSUARIO, TABELAORIGEM, DATAALTERACAO, VALORANTERIOR) 
  VALUES 
  (idTRILHA_AUDITORIA_SEQUENCE.NEXTVAL, 
  :old.IDUSUARIO,
  'USUARIO', 
  SYSDATE, 
  TO_CHAR (:old.IDUSUARIO) || ' ; ' || (:old.NOME) || ' ; ' || (:old.SOBRENOME) || ' ; ' || (:old.TELEFONE) || ' ; ' || (:old.EMAIL) ||  ' ; ' || (:old.SENHA) || ' ; ' || (:old.FOTO));
END;




create or replace TRIGGER AUDITORIA_CARRO
BEFORE UPDATE OR DELETE ON CARRO
FOR EACH ROW
BEGIN
  INSERT INTO TRILHA_AUDITORIA (IDTRILHA_AUDITORIA, USUARIO_IDUSUARIO, TABELAORIGEM, DATAALTERACAO, VALORANTERIOR) 
  VALUES 
  (idTRILHA_AUDITORIA_SEQUENCE.NEXTVAL, 
  :old.USUARIO_IDUSUARIO,
  'CARRO', 
  SYSDATE, 
  TO_CHAR (:old.IDCARRO) || ' ; ' || (:old.TPCOMBUST_IDTPCOMBUST) || ' ; ' || (:old.USUARIO_IDUSUARIO) || ' ; ' || 
  (:old.APELIDOCARRO) || ' ; ' || (:old.MARCA)  || ' ; ' || (:old.MODELO) || ' ; ' || (:old.ANOFABRICACAO) || ' ; ' || 
  (:old.ANOMODELO) || ' ; ' || (:old.COR) || ' ; ' || (:old.PLACA) || ' ; ' || (:old.KILOMETRAGEM) || ' ; ' || (:old.FOTO)  );
END;





create or replace TRIGGER AUDITORIA_ACESSORIOS
BEFORE UPDATE OR DELETE ON ACESSORIOS
FOR EACH ROW
BEGIN
  INSERT INTO TRILHA_AUDITORIA (IDTRILHA_AUDITORIA, USUARIO_IDUSUARIO, TABELAORIGEM, DATAALTERACAO, VALORANTERIOR) 
  VALUES 
  (idTRILHA_AUDITORIA_SEQUENCE.NEXTVAL, 
  (SELECT USUARIO_IDUSUARIO FROM CARRO WHERE IDCARRO = :old.CARRO_IDCARRO),
  'ACESSORIOS', 
  SYSDATE, 
  TO_CHAR (:old.IDACESSORIOS) || ' ; ' || (:old.CARRO_IDCARRO) || ' ; ' || (:old.NOME) || ' ; ' || 
  (:old.DESCRICAO) || ' ; ' || (:old.MARCA)  || ' ; ' || (:old.MODELO) || ' ; ' || (:old.FOTO) );
END;