
INSERT INTO TPCOMBUST (IDTPCOMBUST, DESCRICAO) VALUES (1, 'FLEX');
INSERT INTO TPCOMBUST (IDTPCOMBUST, DESCRICAO) VALUES (2, 'GASOLINA');
INSERT INTO TPCOMBUST (IDTPCOMBUST, DESCRICAO) VALUES (3, 'ALCOOL');

INSERT INTO TIPO_GRUPO (IDTIPO_GRUPO, DESC_TP_GRUPO) VALUES (1, 'AMIGO');
INSERT INTO TIPO_GRUPO (IDTIPO_GRUPO, DESC_TP_GRUPO) VALUES (2, 'EVENTO');
INSERT INTO TIPO_GRUPO (IDTIPO_GRUPO, DESC_TP_GRUPO) VALUES (3, 'GRUPO');

INSERT INTO USUARIO (IDUSUARIO,NOME,SOBRENOME,TELEFONE,EMAIL,SENHA,FOTO) VALUES (idUsuario_SEQUENCE.NEXTVAL,'admin','master','0800100001','admin@mygarage.com','admin','S');
INSERT INTO USUARIO (IDUSUARIO,NOME,SOBRENOME,TELEFONE,EMAIL,SENHA,FOTO) VALUES (idUsuario_SEQUENCE.NEXTVAL,'Juliano','Zapelini','554199996860','zapelini@mygarage.com','juliano','S');
INSERT INTO USUARIO (IDUSUARIO,NOME,SOBRENOME,TELEFONE,EMAIL,SENHA,FOTO) VALUES (idUsuario_SEQUENCE.NEXTVAL,'Tiago','Mazzer','554188886860','mazzer@mygarage.com','tiago','S');
INSERT INTO USUARIO (IDUSUARIO,NOME,SOBRENOME,TELEFONE,EMAIL,SENHA,FOTO) VALUES (idUsuario_SEQUENCE.NEXTVAL,'Joao','Batista','554188889999','joao@mygarage.com','joao','S');
INSERT INTO USUARIO (IDUSUARIO,NOME,SOBRENOME,TELEFONE,EMAIL,SENHA,FOTO) VALUES (idUsuario_SEQUENCE.NEXTVAL,'Maria','Silva','554133299999','maria@mygarage.com','maria','S');
INSERT INTO USUARIO (IDUSUARIO,NOME,SOBRENOME,TELEFONE,EMAIL,SENHA,FOTO) VALUES (idUsuario_SEQUENCE.NEXTVAL,'Pedro','Rocha','554133291234','pedro@mygarage.com','pedro','S');
INSERT INTO USUARIO (IDUSUARIO,NOME,SOBRENOME,TELEFONE,EMAIL,SENHA,FOTO) VALUES (idUsuario_SEQUENCE.NEXTVAL,'Ana Paula','Pereira','554133451234','anapaula@mygarage.com','anapaula','S');
INSERT INTO USUARIO (IDUSUARIO,NOME,SOBRENOME,TELEFONE,EMAIL,SENHA,FOTO) VALUES (idUsuario_SEQUENCE.NEXTVAL,'Antonio','Nunes','554898675768','antonio@mygarage.com','antonio','S');
INSERT INTO USUARIO (IDUSUARIO,NOME,SOBRENOME,TELEFONE,EMAIL,SENHA,FOTO) VALUES (idUsuario_SEQUENCE.NEXTVAL,'Luis','Alberto','554124242424','luis@mygarage.com','luis','S');

INSERT INTO CARRO (IDCARRO, TPCOMBUST_IDTPCOMBUST, USUARIO_IDUSUARIO, APELIDOCARRO, MARCA, MODELO, ANOFABRICACAO, ANOMODELO, COR, PLACA, KILOMETRAGEM, FOTO) VALUES (IDCARRO_SEQUENCE.NEXTVAL, 2, 1, 'Carro do Sonho', 'Chevrolet', 'Caravan', '1984', '1984', 'Dourado', 'AAA-9876', 180000, 'S');
INSERT INTO CARRO (IDCARRO, TPCOMBUST_IDTPCOMBUST, USUARIO_IDUSUARIO, APELIDOCARRO, MARCA, MODELO, ANOFABRICACAO, ANOMODELO, COR, PLACA, KILOMETRAGEM, FOTO) VALUES (IDCARRO_SEQUENCE.NEXTVAL, 3, 2, 'Jujuba', 'Volkswagen', 'Gol', '2002', '2002', 'Prata', 'ABF-1223', 140000, 'S');
INSERT INTO CARRO (IDCARRO, TPCOMBUST_IDTPCOMBUST, USUARIO_IDUSUARIO, APELIDOCARRO, MARCA, MODELO, ANOFABRICACAO, ANOMODELO, COR, PLACA, KILOMETRAGEM, FOTO) VALUES (IDCARRO_SEQUENCE.NEXTVAL, 2, 3, 'Astrão', 'Opel', 'Astra', '2002', '2002', 'Prata', 'ASZ-9126', 121000, 'S');
INSERT INTO CARRO (IDCARRO, TPCOMBUST_IDTPCOMBUST, USUARIO_IDUSUARIO, APELIDOCARRO, MARCA, MODELO, ANOFABRICACAO, ANOMODELO, COR, PLACA, KILOMETRAGEM, FOTO) VALUES (IDCARRO_SEQUENCE.NEXTVAL, 3, 3, 'Turbão', 'Volksvagen', 'Passat', '1984', '1984', 'Branco', 'AIG-5194', 150000, 'S');
INSERT INTO CARRO (IDCARRO, TPCOMBUST_IDTPCOMBUST, USUARIO_IDUSUARIO, APELIDOCARRO, MARCA, MODELO, ANOFABRICACAO, ANOMODELO, COR, PLACA, KILOMETRAGEM, FOTO) VALUES (IDCARRO_SEQUENCE.NEXTVAL, 2, 3, 'Red', 'Honda', 'Civic SI', '2008', '2008', 'Vermelho', 'ASI-2008', 90000, 'S');
INSERT INTO CARRO (IDCARRO, TPCOMBUST_IDTPCOMBUST, USUARIO_IDUSUARIO, APELIDOCARRO, MARCA, MODELO, ANOFABRICACAO, ANOMODELO, COR, PLACA, KILOMETRAGEM, FOTO) VALUES (IDCARRO_SEQUENCE.NEXTVAL, 1, 5, 'Faísca', 'Renault', 'Sandero RS', '2015', '2015', 'Branco', 'ARS-2015', 50, 'S');
INSERT INTO CARRO (IDCARRO, TPCOMBUST_IDTPCOMBUST, USUARIO_IDUSUARIO, APELIDOCARRO, MARCA, MODELO, ANOFABRICACAO, ANOMODELO, COR, PLACA, KILOMETRAGEM, FOTO) VALUES (IDCARRO_SEQUENCE.NEXTVAL, 2, 5, 'POF', 'Volksvagen', 'Voyage', '1982', '1982', 'Azul', 'AWE-4398', 140000, 'S');
INSERT INTO CARRO (IDCARRO, TPCOMBUST_IDTPCOMBUST, USUARIO_IDUSUARIO, APELIDOCARRO, MARCA, MODELO, ANOFABRICACAO, ANOMODELO, COR, PLACA, KILOMETRAGEM, FOTO) VALUES (IDCARRO_SEQUENCE.NEXTVAL, 2, 6, 'Chumbinho', 'Renault', 'Clio', '2004', '2004', 'Chumbo', 'ADE-3243', 80000, 'S');
INSERT INTO CARRO (IDCARRO, TPCOMBUST_IDTPCOMBUST, USUARIO_IDUSUARIO, APELIDOCARRO, MARCA, MODELO, ANOFABRICACAO, ANOMODELO, COR, PLACA, KILOMETRAGEM, FOTO) VALUES (IDCARRO_SEQUENCE.NEXTVAL, 2, 8, 'Possante', 'Toyota', 'Prius', '2014', '2014', 'Prata', 'ADS-4353', 80000, 'S');

INSERT INTO ACESSORIOS (IDACESSORIOS, CARRO_IDCARRO, NOME, DESCRICAO, MARCA, MODELO, FOTO) VALUES (IDACESSORIOS_SEQUENCE.NEXTVAL, 3, 'Emblema Opel', 'Emblemas originais da OPEL', 'Opel', 'Original', 'S');  
INSERT INTO ACESSORIOS (IDACESSORIOS, CARRO_IDCARRO, NOME, DESCRICAO, MARCA, MODELO, FOTO) VALUES (IDACESSORIOS_SEQUENCE.NEXTVAL, 4, 'Turbo', 'Turbina', 'Master Power', '.48 .42', 'S');  
INSERT INTO ACESSORIOS (IDACESSORIOS, CARRO_IDCARRO, NOME, DESCRICAO, MARCA, MODELO, FOTO) VALUES (IDACESSORIOS_SEQUENCE.NEXTVAL, 5, 'Filtro', 'Filtro', 'KeN', '.48 .42', 'S');  
INSERT INTO ACESSORIOS (IDACESSORIOS, CARRO_IDCARRO, NOME, DESCRICAO, MARCA, MODELO, FOTO) VALUES (IDACESSORIOS_SEQUENCE.NEXTVAL, 5, 'Escape', 'Inox', 'KeN', 'Catdelete', 'S'); 
INSERT INTO ACESSORIOS (IDACESSORIOS, CARRO_IDCARRO, NOME, DESCRICAO, MARCA, MODELO, FOTO) VALUES (IDACESSORIOS_SEQUENCE.NEXTVAL, 8, 'Chip', 'Top', 'Racing Chips', '2.0', 'S'); 
INSERT INTO ACESSORIOS (IDACESSORIOS, CARRO_IDCARRO, NOME, DESCRICAO, MARCA, MODELO, FOTO) VALUES (IDACESSORIOS_SEQUENCE.NEXTVAL, 9, 'Bateria Solar', 'Bateria', 'Bateria do zézão', 'top', 'S');

INSERT INTO CODIGO_AMIGO (IDCODIGO_AMIGO, USUARIO_IDUSUARIO) VALUES (IDCODIGO_AMIGO_SEQUENCE.NEXTVAL, 1);
INSERT INTO CODIGO_AMIGO (IDCODIGO_AMIGO, USUARIO_IDUSUARIO) VALUES (IDCODIGO_AMIGO_SEQUENCE.NEXTVAL, 2);
INSERT INTO CODIGO_AMIGO (IDCODIGO_AMIGO, USUARIO_IDUSUARIO) VALUES (IDCODIGO_AMIGO_SEQUENCE.NEXTVAL, 3);
INSERT INTO CODIGO_AMIGO (IDCODIGO_AMIGO, USUARIO_IDUSUARIO) VALUES (IDCODIGO_AMIGO_SEQUENCE.NEXTVAL, 4);
INSERT INTO CODIGO_AMIGO (IDCODIGO_AMIGO, USUARIO_IDUSUARIO) VALUES (IDCODIGO_AMIGO_SEQUENCE.NEXTVAL, 5);
INSERT INTO CODIGO_AMIGO (IDCODIGO_AMIGO, USUARIO_IDUSUARIO) VALUES (IDCODIGO_AMIGO_SEQUENCE.NEXTVAL, 6);
INSERT INTO CODIGO_AMIGO (IDCODIGO_AMIGO, USUARIO_IDUSUARIO) VALUES (IDCODIGO_AMIGO_SEQUENCE.NEXTVAL, 7);
INSERT INTO CODIGO_AMIGO (IDCODIGO_AMIGO, USUARIO_IDUSUARIO) VALUES (IDCODIGO_AMIGO_SEQUENCE.NEXTVAL, 8);
INSERT INTO CODIGO_AMIGO (IDCODIGO_AMIGO, USUARIO_IDUSUARIO) VALUES (IDCODIGO_AMIGO_SEQUENCE.NEXTVAL, 9);


INSERT INTO RELACIONAMENTO (IDRELACIONAMENTO,CODIGO_AMIGO_IDCODIGO_AMIGO,USUARIO_IDUSUARIO,TIPO_GRUPO_IDTIPO_GRUPO,DTINICIORELACIONAMENTO,DTFIMRELACIONAMENTO,STATUSRELACIONAMENTO) VALUES (IDRELACIONAMENTO_SEQUENCE.NEXTVAL, 1, 1, 1, SYSDATE, NULL, 'A');
INSERT INTO RELACIONAMENTO (IDRELACIONAMENTO,CODIGO_AMIGO_IDCODIGO_AMIGO,USUARIO_IDUSUARIO,TIPO_GRUPO_IDTIPO_GRUPO,DTINICIORELACIONAMENTO,DTFIMRELACIONAMENTO,STATUSRELACIONAMENTO) VALUES (IDRELACIONAMENTO_SEQUENCE.NEXTVAL, 2, 2, 1, SYSDATE, NULL, 'A');
INSERT INTO RELACIONAMENTO (IDRELACIONAMENTO,CODIGO_AMIGO_IDCODIGO_AMIGO,USUARIO_IDUSUARIO,TIPO_GRUPO_IDTIPO_GRUPO,DTINICIORELACIONAMENTO,DTFIMRELACIONAMENTO,STATUSRELACIONAMENTO) VALUES (IDRELACIONAMENTO_SEQUENCE.NEXTVAL, 3, 3, 1, SYSDATE, NULL, 'A');
INSERT INTO RELACIONAMENTO (IDRELACIONAMENTO,CODIGO_AMIGO_IDCODIGO_AMIGO,USUARIO_IDUSUARIO,TIPO_GRUPO_IDTIPO_GRUPO,DTINICIORELACIONAMENTO,DTFIMRELACIONAMENTO,STATUSRELACIONAMENTO) VALUES (IDRELACIONAMENTO_SEQUENCE.NEXTVAL, 4, 4, 1, SYSDATE, NULL, 'A');
INSERT INTO RELACIONAMENTO (IDRELACIONAMENTO,CODIGO_AMIGO_IDCODIGO_AMIGO,USUARIO_IDUSUARIO,TIPO_GRUPO_IDTIPO_GRUPO,DTINICIORELACIONAMENTO,DTFIMRELACIONAMENTO,STATUSRELACIONAMENTO) VALUES (IDRELACIONAMENTO_SEQUENCE.NEXTVAL, 5, 5, 1, SYSDATE, NULL, 'A');
INSERT INTO RELACIONAMENTO (IDRELACIONAMENTO,CODIGO_AMIGO_IDCODIGO_AMIGO,USUARIO_IDUSUARIO,TIPO_GRUPO_IDTIPO_GRUPO,DTINICIORELACIONAMENTO,DTFIMRELACIONAMENTO,STATUSRELACIONAMENTO) VALUES (IDRELACIONAMENTO_SEQUENCE.NEXTVAL, 6, 6, 1, SYSDATE, NULL, 'A');
INSERT INTO RELACIONAMENTO (IDRELACIONAMENTO,CODIGO_AMIGO_IDCODIGO_AMIGO,USUARIO_IDUSUARIO,TIPO_GRUPO_IDTIPO_GRUPO,DTINICIORELACIONAMENTO,DTFIMRELACIONAMENTO,STATUSRELACIONAMENTO) VALUES (IDRELACIONAMENTO_SEQUENCE.NEXTVAL, 7, 7, 1, SYSDATE, NULL, 'A');
INSERT INTO RELACIONAMENTO (IDRELACIONAMENTO,CODIGO_AMIGO_IDCODIGO_AMIGO,USUARIO_IDUSUARIO,TIPO_GRUPO_IDTIPO_GRUPO,DTINICIORELACIONAMENTO,DTFIMRELACIONAMENTO,STATUSRELACIONAMENTO) VALUES (IDRELACIONAMENTO_SEQUENCE.NEXTVAL, 8, 8, 1, SYSDATE, NULL, 'A');
INSERT INTO RELACIONAMENTO (IDRELACIONAMENTO,CODIGO_AMIGO_IDCODIGO_AMIGO,USUARIO_IDUSUARIO,TIPO_GRUPO_IDTIPO_GRUPO,DTINICIORELACIONAMENTO,DTFIMRELACIONAMENTO,STATUSRELACIONAMENTO) VALUES (IDRELACIONAMENTO_SEQUENCE.NEXTVAL, 9, 9, 1, SYSDATE, NULL, 'A');


Insert into TIMELINE (IDTIMELINE,USUARIO_IDUSUARIO,DATACADASTRO,DESCRICAO) values (IDTIMELINE_SEQUENCE.NEXTVAL,5,to_date('01/05/16','DD/MM/RR'),'TESTE DE POST1');
Insert into TIMELINE (IDTIMELINE,USUARIO_IDUSUARIO,DATACADASTRO,DESCRICAO) values (IDTIMELINE_SEQUENCE.NEXTVAL,5,to_date('02/05/16','DD/MM/RR'),'TESTE DE POST2');
Insert into TIMELINE (IDTIMELINE,USUARIO_IDUSUARIO,DATACADASTRO,DESCRICAO) values (IDTIMELINE_SEQUENCE.NEXTVAL,4,to_date('03/05/16','DD/MM/RR'),'TESTE DE POST3');
Insert into TIMELINE (IDTIMELINE,USUARIO_IDUSUARIO,DATACADASTRO,DESCRICAO) values (IDTIMELINE_SEQUENCE.NEXTVAL,4,to_date('04/05/16','DD/MM/RR'),'TESTE DE POST4');
Insert into TIMELINE (IDTIMELINE,USUARIO_IDUSUARIO,DATACADASTRO,DESCRICAO) values (IDTIMELINE_SEQUENCE.NEXTVAL,2,to_date('05/05/16','DD/MM/RR'),'TESTE DE POST5');
Insert into TIMELINE (IDTIMELINE,USUARIO_IDUSUARIO,DATACADASTRO,DESCRICAO) values (IDTIMELINE_SEQUENCE.NEXTVAL,2,to_date('06/05/16','DD/MM/RR'),'TESTE DE POST6');
Insert into TIMELINE (IDTIMELINE,USUARIO_IDUSUARIO,DATACADASTRO,DESCRICAO) values (IDTIMELINE_SEQUENCE.NEXTVAL,3,to_date('07/05/16','DD/MM/RR'),'TESTE DE POST7');
Insert into TIMELINE (IDTIMELINE,USUARIO_IDUSUARIO,DATACADASTRO,DESCRICAO) values (IDTIMELINE_SEQUENCE.NEXTVAL,3,to_date('08/05/16','DD/MM/RR'),'TESTE DE POST8');
Insert into TIMELINE (IDTIMELINE,USUARIO_IDUSUARIO,DATACADASTRO,DESCRICAO) values (IDTIMELINE_SEQUENCE.NEXTVAL,1,to_date('08/05/16','DD/MM/RR'),'Olaaaa');
Insert into TIMELINE (IDTIMELINE,USUARIO_IDUSUARIO,DATACADASTRO,DESCRICAO) values (IDTIMELINE_SEQUENCE.NEXTVAL,6,to_date('08/05/16','DD/MM/RR'),'Meu id é o seis');
Insert into TIMELINE (IDTIMELINE,USUARIO_IDUSUARIO,DATACADASTRO,DESCRICAO) values (IDTIMELINE_SEQUENCE.NEXTVAL,7,to_date('08/05/16','DD/MM/RR'),'ola Meu id é o sete');
Insert into TIMELINE (IDTIMELINE,USUARIO_IDUSUARIO,DATACADASTRO,DESCRICAO) values (IDTIMELINE_SEQUENCE.NEXTVAL,8,to_date('08/05/16','DD/MM/RR'),'teste oito');

Insert into TIMELINE_ACAO (IDTIMELINE_ACAO, USUARIO_IDUSUARIO, TIMELINE_IDTIMELINE, DATAACAO, CURTIR, COMENTARIO) values (IDTIMELINE_ACAO_SEQUENCE.NEXTVAL, 1, 1, SYSDATE, NULL, 'COMENTARIO 1');
Insert into TIMELINE_ACAO (IDTIMELINE_ACAO, USUARIO_IDUSUARIO, TIMELINE_IDTIMELINE, DATAACAO, CURTIR, COMENTARIO) values (IDTIMELINE_ACAO_SEQUENCE.NEXTVAL, 1, 1, SYSDATE, 'S' ,  NULL);
Insert into TIMELINE_ACAO (IDTIMELINE_ACAO, USUARIO_IDUSUARIO, TIMELINE_IDTIMELINE, DATAACAO, CURTIR, COMENTARIO) values (IDTIMELINE_ACAO_SEQUENCE.NEXTVAL, 2, 2, SYSDATE, NULL, 'COMENTARIO 2');
Insert into TIMELINE_ACAO (IDTIMELINE_ACAO, USUARIO_IDUSUARIO, TIMELINE_IDTIMELINE, DATAACAO, CURTIR, COMENTARIO) values (IDTIMELINE_ACAO_SEQUENCE.NEXTVAL, 2, 2, SYSDATE, 'S',   NULL);
Insert into TIMELINE_ACAO (IDTIMELINE_ACAO, USUARIO_IDUSUARIO, TIMELINE_IDTIMELINE, DATAACAO, CURTIR, COMENTARIO) values (IDTIMELINE_ACAO_SEQUENCE.NEXTVAL, 3, 4, SYSDATE, NULL, 'COMENTARIO 3');
Insert into TIMELINE_ACAO (IDTIMELINE_ACAO, USUARIO_IDUSUARIO, TIMELINE_IDTIMELINE, DATAACAO, CURTIR, COMENTARIO) values (IDTIMELINE_ACAO_SEQUENCE.NEXTVAL, 4, 4, SYSDATE, NULL, 'COMENTARIO 4');
Insert into TIMELINE_ACAO (IDTIMELINE_ACAO, USUARIO_IDUSUARIO, TIMELINE_IDTIMELINE, DATAACAO, CURTIR, COMENTARIO) values (IDTIMELINE_ACAO_SEQUENCE.NEXTVAL, 4, 4, SYSDATE, NULL, 'COMENTARIO 5');
Insert into TIMELINE_ACAO (IDTIMELINE_ACAO, USUARIO_IDUSUARIO, TIMELINE_IDTIMELINE, DATAACAO, CURTIR, COMENTARIO) values (IDTIMELINE_ACAO_SEQUENCE.NEXTVAL, 4, 4, SYSDATE, 'S', NULL);
Insert into TIMELINE_ACAO (IDTIMELINE_ACAO, USUARIO_IDUSUARIO, TIMELINE_IDTIMELINE, DATAACAO, CURTIR, COMENTARIO) values (IDTIMELINE_ACAO_SEQUENCE.NEXTVAL, 5, 5, SYSDATE, 'S', NULL);
Insert into TIMELINE_ACAO (IDTIMELINE_ACAO, USUARIO_IDUSUARIO, TIMELINE_IDTIMELINE, DATAACAO, CURTIR, COMENTARIO) values (IDTIMELINE_ACAO_SEQUENCE.NEXTVAL, 1, 4, SYSDATE, NULL, 'COMENTARIO 6');

INSERT INTO ADMINISTRADOR (IDUSUARIO,NOME,SOBRENOME, FOTO, TELEFONE,EMAIL,SENHA, CPF) VALUES (ADMUSUARIO_SEQUENCE.NEXTVAL,'admin','master', NULL, '0800100001','admin@mygarage.com','admin', '111.111.111-11');
INSERT INTO ADMINISTRADOR (IDUSUARIO,NOME,SOBRENOME, FOTO, TELEFONE,EMAIL,SENHA, CPF) VALUES (ADMUSUARIO_SEQUENCE.NEXTVAL,'Juliano','Zapelini', NULL, '554199996860','zapelini@mygarage.com','juliano', '041.248.859-03');
INSERT INTO ADMINISTRADOR (IDUSUARIO,NOME,SOBRENOME, FOTO, TELEFONE,EMAIL,SENHA, CPF) VALUES (ADMUSUARIO_SEQUENCE.NEXTVAL,'Tiago','Mazzer', NULL, '554188886860','mazzer@mygarage.com','tiago', '048.140.269-19');

INSERT INTO TRILHA_AUDITORIA (IDTRILHA_AUDITORIA, USUARIO_IDUSUARIO, TABELAORIGEM, DATAALTERACAO, VALORANTERIOR) VALUES (idTRILHA_AUDITORIA_SEQUENCE.NEXTVAL, 1, 'CARRO', SYSDATE, '1;TIAGO;MAZZER;04123498563;MAZER@GMAIL.COM;SENHA;S');

commit;