DROP TRIGGER AUDITORIA_USUARIO;
DROP TRIGGER AUDITORIA_CARRO;
DROP TRIGGER AUDITORIA_ACESSORIOS;

DROP FUNCTION COUNT_COMENTARIOS;
DROP FUNCTION COUNT_LIKES;

DROP PROCEDURE MONTATIMELINE;
-----------------------------------------------------

DELETE FROM OPCIONAISCARRO;
DROP TABLE OPCIONAISCARRO;

DELETE FROM TIPO_GRUPO;
DROP TABLE TIPO_GRUPO;

DELETE FROM ACESSORIOS;
DROP SEQUENCE IDACESSORIOS_SEQUENCE;
DROP TABLE ACESSORIOS;

DELETE FROM CARRO;
DROP SEQUENCE idCarro_SEQUENCE;
DROP TABLE CARRO;

DELETE FROM TPCOMBUST;
DROP TABLE TPCOMBUST;

DELETE FROM ADMINISTRADOR;
DROP SEQUENCE ADMUSUARIO_SEQUENCE;
DROP TABLE ADMINISTRADOR;

DELETE FROM TRILHA_AUDITORIA;
DROP SEQUENCE idTRILHA_AUDITORIA_SEQUENCE;
DROP TABLE TRILHA_AUDITORIA;

DELETE FROM EVENTO;
DROP TABLE EVENTO;

DELETE FROM GRUPO_DISCUSSAO_ACAO;
DROP TABLE GRUPO_DISCUSSAO_ACAO;

DELETE FROM GRUPO_DISCUSSAO;
DROP TABLE GRUPO_DISCUSSAO;

DELETE FROM LOG;
DROP SEQUENCE LOG_SEQUENCE;
DROP TABLE LOG;

DELETE FROM RELACIONAMENTO;
DROP SEQUENCE IDRELACIONAMENTO_SEQUENCE;
DROP TABLE RELACIONAMENTO;

DELETE FROM CODIGO_AMIGO;
DROP SEQUENCE IDCODIGO_AMIGO_SEQUENCE;
DROP TABLE CODIGO_AMIGO;

DELETE FROM TIMELINE_ACAO;
DROP SEQUENCE IDTIMELINE_ACAO_SEQUENCE;
DROP TABLE TIMELINE_ACAO;

DELETE FROM TIMELINE;
DROP SEQUENCE IDTIMELINE_SEQUENCE;
DROP TABLE TIMELINE;

DELETE FROM USUARIO;
DROP SEQUENCE idUsuario_SEQUENCE;
DROP TABLE USUARIO;