==================================================================
=====================CARRO==============================
==================================================================


DELETE FROM CARRO;

DROP SEQUENCE idCarro_SEQUENCE;

CREATE SEQUENCE idCarro_SEQUENCE 
MINVALUE 1
MAXVALUE 100000
INCREMENT BY 1
START WITH 1;

COMMIT;
==================================================================
=================USUARIO==========================================
==================================================================

DELETE FROM USUARIO;

DROP SEQUENCE idUsuario_SEQUENCE;

CREATE SEQUENCE idUsuario_SEQUENCE 
MINVALUE 1
MAXVALUE 100000
INCREMENT BY 1
START WITH 1;

INSERT INTO USUARIO (IDUSUARIO,NOME,SOBRENOME,TELEFONE,EMAIL,SENHA) VALUES (idUsuario_SEQUENCE.NEXTVAL,'admin','master','0800100001','admin@mygarage.com','admin');
INSERT INTO USUARIO (IDUSUARIO,NOME,SOBRENOME,TELEFONE,EMAIL,SENHA) VALUES (idUsuario_SEQUENCE.NEXTVAL,'Juliano','Zapelini','554199996860','zapelini@mygarage.com','juliano');
INSERT INTO USUARIO (IDUSUARIO,NOME,SOBRENOME,TELEFONE,EMAIL,SENHA) VALUES (idUsuario_SEQUENCE.NEXTVAL,'Tiago','Mazzer','554188886860','mazzer@mygarage.com','tiago');
INSERT INTO USUARIO (IDUSUARIO,NOME,SOBRENOME,TELEFONE,EMAIL,SENHA) VALUES (idUsuario_SEQUENCE.NEXTVAL,'admin','master','0800100001','admin@mygarage.com','admin');
INSERT INTO USUARIO (IDUSUARIO,NOME,SOBRENOME,TELEFONE,EMAIL,SENHA) VALUES (idUsuario_SEQUENCE.NEXTVAL,'Joao','Batista','554188889999','joao@mygarage.com','joao');
INSERT INTO USUARIO (IDUSUARIO,NOME,SOBRENOME,TELEFONE,EMAIL,SENHA) VALUES (idUsuario_SEQUENCE.NEXTVAL,'Maria','Silva','554133299999','maria@mygarage.com','maria');
INSERT INTO USUARIO (IDUSUARIO,NOME,SOBRENOME,TELEFONE,EMAIL,SENHA) VALUES (idUsuario_SEQUENCE.NEXTVAL,'Pedro','Rocha','554133291234','pedro@mygarage.com','pedro');
INSERT INTO USUARIO (IDUSUARIO,NOME,SOBRENOME,TELEFONE,EMAIL,SENHA) VALUES (idUsuario_SEQUENCE.NEXTVAL,'Ana Paula','Pereira','554133451234','anapaula@mygarage.com','anapaula');

COMMIT;
SELECT * FROM USUARIO;

==================================================================
=================CODIGO_AMIGO=====================================
==================================================================

DELETE FROM CODIGO_AMIGO;

DROP SEQUENCE IDCODIGO_AMIGO_SEQUENCE;

CREATE SEQUENCE IDCODIGO_AMIGO_SEQUENCE 
MINVALUE 1
MAXVALUE 100000
INCREMENT BY 1
START WITH 1;

INSERT INTO CODIGO_AMIGO (IDCODIGO_AMIGO, USUARIO_IDUSUARIO) VALUES (IDCODIGO_AMIGO_SEQUENCE.NEXTVAL, 1);
INSERT INTO CODIGO_AMIGO (IDCODIGO_AMIGO, USUARIO_IDUSUARIO) VALUES (IDCODIGO_AMIGO_SEQUENCE.NEXTVAL, 2);
INSERT INTO CODIGO_AMIGO (IDCODIGO_AMIGO, USUARIO_IDUSUARIO) VALUES (IDCODIGO_AMIGO_SEQUENCE.NEXTVAL, 3);
INSERT INTO CODIGO_AMIGO (IDCODIGO_AMIGO, USUARIO_IDUSUARIO) VALUES (IDCODIGO_AMIGO_SEQUENCE.NEXTVAL, 4);
INSERT INTO CODIGO_AMIGO (IDCODIGO_AMIGO, USUARIO_IDUSUARIO) VALUES (IDCODIGO_AMIGO_SEQUENCE.NEXTVAL, 5);
INSERT INTO CODIGO_AMIGO (IDCODIGO_AMIGO, USUARIO_IDUSUARIO) VALUES (IDCODIGO_AMIGO_SEQUENCE.NEXTVAL, 6);
INSERT INTO CODIGO_AMIGO (IDCODIGO_AMIGO, USUARIO_IDUSUARIO) VALUES (IDCODIGO_AMIGO_SEQUENCE.NEXTVAL, 7);

COMMIT;

SELECT * FROM CODIGO_AMIGO;

==================================================================
=================RELACIONAMENTO=====================================
==================================================================

DELETE FROM RELACIONAMENTO;

DROP SEQUENCE IDRELACIONAMENTO_SEQUENCE;

CREATE SEQUENCE IDRELACIONAMENTO_SEQUENCE 
MINVALUE 1
MAXVALUE 100000
INCREMENT BY 1
START WITH 1;

INSERT INTO RELACIONAMENTO VALUES (IDRELACIONAMENTO_SEQUENCE.NEXTVAL, 1, 1, 1, SYSDATE, NULL, 'A');
INSERT INTO RELACIONAMENTO VALUES (IDRELACIONAMENTO_SEQUENCE.NEXTVAL, 2, 2, 1, SYSDATE, NULL, 'A');
INSERT INTO RELACIONAMENTO VALUES (IDRELACIONAMENTO_SEQUENCE.NEXTVAL, 3, 3, 1, SYSDATE, NULL, 'A');
INSERT INTO RELACIONAMENTO VALUES (IDRELACIONAMENTO_SEQUENCE.NEXTVAL, 4, 4, 1, SYSDATE, NULL, 'A');
INSERT INTO RELACIONAMENTO VALUES (IDRELACIONAMENTO_SEQUENCE.NEXTVAL, 5, 5, 1, SYSDATE, NULL, 'A');
INSERT INTO RELACIONAMENTO VALUES (IDRELACIONAMENTO_SEQUENCE.NEXTVAL, 6, 6, 1, SYSDATE, NULL, 'A');
INSERT INTO RELACIONAMENTO VALUES (IDRELACIONAMENTO_SEQUENCE.NEXTVAL, 7, 7, 1, SYSDATE, NULL, 'A');
INSERT INTO RELACIONAMENTO VALUES (IDRELACIONAMENTO_SEQUENCE.NEXTVAL, 8, 8, 1, SYSDATE, NULL, 'A');

COMMIT;
SELECT * FROM RELACIONAMENTO;

==================================================================
=================TIMELINE=====================================
==================================================================

DELETE FROM TIMELINE;

DROP SEQUENCE IDTIMELINE_SEQUENCE;

CREATE SEQUENCE IDTIMELINE_SEQUENCE 
MINVALUE 1
MAXVALUE 100000
INCREMENT BY 1
START WITH 1;

Insert into TIMELINE (IDTIMELINE,USUARIO_IDUSUARIO,DATACADASTRO,DESCRICAO) values (IDTIMELINE_SEQUENCE.NEXTVAL,5,to_date('01/05/16','DD/MM/RR'),'TESTE DE POST1');
Insert into TIMELINE (IDTIMELINE,USUARIO_IDUSUARIO,DATACADASTRO,DESCRICAO) values (IDTIMELINE_SEQUENCE.NEXTVAL,5,to_date('02/05/16','DD/MM/RR'),'TESTE DE POST2');
Insert into TIMELINE (IDTIMELINE,USUARIO_IDUSUARIO,DATACADASTRO,DESCRICAO) values (IDTIMELINE_SEQUENCE.NEXTVAL,4,to_date('03/05/16','DD/MM/RR'),'TESTE DE POST3');
Insert into TIMELINE (IDTIMELINE,USUARIO_IDUSUARIO,DATACADASTRO,DESCRICAO) values (IDTIMELINE_SEQUENCE.NEXTVAL,4,to_date('04/05/16','DD/MM/RR'),'TESTE DE POST4');
Insert into TIMELINE (IDTIMELINE,USUARIO_IDUSUARIO,DATACADASTRO,DESCRICAO) values (IDTIMELINE_SEQUENCE.NEXTVAL,2,to_date('05/05/16','DD/MM/RR'),'TESTE DE POST5');
Insert into TIMELINE (IDTIMELINE,USUARIO_IDUSUARIO,DATACADASTRO,DESCRICAO) values (IDTIMELINE_SEQUENCE.NEXTVAL,2,to_date('06/05/16','DD/MM/RR'),'TESTE DE POST6');
Insert into TIMELINE (IDTIMELINE,USUARIO_IDUSUARIO,DATACADASTRO,DESCRICAO) values (IDTIMELINE_SEQUENCE.NEXTVAL,3,to_date('07/05/16','DD/MM/RR'),'TESTE DE POST7');
Insert into TIMELINE (IDTIMELINE,USUARIO_IDUSUARIO,DATACADASTRO,DESCRICAO) values (IDTIMELINE_SEQUENCE.NEXTVAL,3,to_date('08/05/16','DD/MM/RR'),'TESTE DE POST8');

COMMIT;
SELECT * FROM TIMELINE;

==================================================================
=================TIMELINE ACAO====================================
==================================================================

DELETE FROM TIMELINE_ACAO;

DROP SEQUENCE IDTIMELINE_ACAO_SEQUENCE;

CREATE SEQUENCE IDTIMELINE_ACAO_SEQUENCE 
MINVALUE 1
MAXVALUE 100000
INCREMENT BY 1
START WITH 1;

Insert into TIMELINE_ACAO (IDTIMELINE_ACAO, USUARIO_IDUSUARIO, TIMELINE_IDTIMELINE, DATAACAO, CURTIR, COMENTARIO) values (IDTIMELINE_ACAO_SEQUENCE.NEXTVAL, 1, 1, SYSDATE, NULL, 'COMENTARIO 1');
Insert into TIMELINE_ACAO (IDTIMELINE_ACAO, USUARIO_IDUSUARIO, TIMELINE_IDTIMELINE, DATAACAO, CURTIR, COMENTARIO) values (IDTIMELINE_ACAO_SEQUENCE.NEXTVAL, 1, 1, SYSDATE, 'S' ,  NULL);
Insert into TIMELINE_ACAO (IDTIMELINE_ACAO, USUARIO_IDUSUARIO, TIMELINE_IDTIMELINE, DATAACAO, CURTIR, COMENTARIO) values (IDTIMELINE_ACAO_SEQUENCE.NEXTVAL, 2, 2, SYSDATE, NULL, 'COMENTARIO 2');
Insert into TIMELINE_ACAO (IDTIMELINE_ACAO, USUARIO_IDUSUARIO, TIMELINE_IDTIMELINE, DATAACAO, CURTIR, COMENTARIO) values (IDTIMELINE_ACAO_SEQUENCE.NEXTVAL, 2, 2, SYSDATE, 'S',   NULL);
Insert into TIMELINE_ACAO (IDTIMELINE_ACAO, USUARIO_IDUSUARIO, TIMELINE_IDTIMELINE, DATAACAO, CURTIR, COMENTARIO) values (IDTIMELINE_ACAO_SEQUENCE.NEXTVAL, 3, 4, SYSDATE, NULL, 'COMENTARIO 3');
Insert into TIMELINE_ACAO (IDTIMELINE_ACAO, USUARIO_IDUSUARIO, TIMELINE_IDTIMELINE, DATAACAO, CURTIR, COMENTARIO) values (IDTIMELINE_ACAO_SEQUENCE.NEXTVAL, 4, 4, SYSDATE, NULL, 'COMENTARIO 4');
Insert into TIMELINE_ACAO (IDTIMELINE_ACAO, USUARIO_IDUSUARIO, TIMELINE_IDTIMELINE, DATAACAO, CURTIR, COMENTARIO) values (IDTIMELINE_ACAO_SEQUENCE.NEXTVAL, 4, 4, SYSDATE, NULL, 'COMENTARIO 5');
Insert into TIMELINE_ACAO (IDTIMELINE_ACAO, USUARIO_IDUSUARIO, TIMELINE_IDTIMELINE, DATAACAO, CURTIR, COMENTARIO) values (IDTIMELINE_ACAO_SEQUENCE.NEXTVAL, 4, 4, SYSDATE, 'S', NULL);
Insert into TIMELINE_ACAO (IDTIMELINE_ACAO, USUARIO_IDUSUARIO, TIMELINE_IDTIMELINE, DATAACAO, CURTIR, COMENTARIO) values (IDTIMELINE_ACAO_SEQUENCE.NEXTVAL, 5, 5, SYSDATE, 'S', NULL);
Insert into TIMELINE_ACAO (IDTIMELINE_ACAO, USUARIO_IDUSUARIO, TIMELINE_IDTIMELINE, DATAACAO, CURTIR, COMENTARIO) values (IDTIMELINE_ACAO_SEQUENCE.NEXTVAL, 1, 4, SYSDATE, NULL, 'COMENTARIO 6');

COMMIT;
SELECT * FROM TIMELINE_ACAO;