DELETE FROM CODIGO_AMIGO;

DROP SEQUENCE IDCODIGO_AMIGO_SEQUENCE;

CREATE SEQUENCE IDCODIGO_AMIGO_SEQUENCE 
MINVALUE 1
MAXVALUE 100000
INCREMENT BY 1
START WITH 1;



DELETE FROM USUARIO;

DROP SEQUENCE idUsuario_SEQUENCE;

CREATE SEQUENCE idUsuario_SEQUENCE 
MINVALUE 1
MAXVALUE 100000
INCREMENT BY 1
START WITH 1;